<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pi_blog"
 *
 * Auto generated by Extension Builder 2016-01-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Pitchart Blog',
	'description' => 'Exercice cours de CMS - Dawin',
	'category' => 'plugin',
	'author' => 'Julien VITTE',
	'author_email' => 'vitte.julien@gmail.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);